// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealEstateAPI.Common.Infrastructure;

#nullable disable

namespace RealEstateAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250819185538_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RealEstateAPI.Features.Properties.Domain.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Bathrooms")
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ListedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MonthlyRent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SquareFeet")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("YearBuilt")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main Street",
                            Bathrooms = 2m,
                            Bedrooms = 3,
                            City = "Houston",
                            IsAvailable = true,
                            ListedDateUtc = new DateTime(2025, 7, 20, 18, 55, 38, 406, DateTimeKind.Utc).AddTicks(1654),
                            MonthlyRent = 1500m,
                            Price = 250000m,
                            PropertyType = "House",
                            SquareFeet = 1500,
                            State = "TX",
                            YearBuilt = 2010,
                            ZipCode = "77001"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Oak Avenue",
                            Bathrooms = 3m,
                            Bedrooms = 4,
                            City = "Austin",
                            IsAvailable = true,
                            ListedDateUtc = new DateTime(2025, 8, 4, 18, 55, 38, 406, DateTimeKind.Utc).AddTicks(1661),
                            MonthlyRent = 2200m,
                            Price = 350000m,
                            PropertyType = "House",
                            SquareFeet = 2200,
                            State = "TX",
                            YearBuilt = 2015,
                            ZipCode = "78701"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Elm Street",
                            Bathrooms = 1m,
                            Bedrooms = 2,
                            City = "Dallas",
                            IsAvailable = false,
                            ListedDateUtc = new DateTime(2025, 7, 5, 18, 55, 38, 406, DateTimeKind.Utc).AddTicks(1662),
                            MonthlyRent = 1200m,
                            Price = 180000m,
                            PropertyType = "Apartment",
                            SquareFeet = 900,
                            State = "TX",
                            YearBuilt = 2018,
                            ZipCode = "75201"
                        },
                        new
                        {
                            Id = 4,
                            Address = "321 Pine Road",
                            Bathrooms = 3.5m,
                            Bedrooms = 5,
                            City = "Houston",
                            IsAvailable = true,
                            ListedDateUtc = new DateTime(2025, 8, 12, 18, 55, 38, 406, DateTimeKind.Utc).AddTicks(1664),
                            MonthlyRent = 2800m,
                            Price = 450000m,
                            PropertyType = "House",
                            SquareFeet = 3000,
                            State = "TX",
                            YearBuilt = 2020,
                            ZipCode = "77002"
                        },
                        new
                        {
                            Id = 5,
                            Address = "555 Sunset Boulevard",
                            Bathrooms = 2.5m,
                            Bedrooms = 3,
                            City = "Austin",
                            IsAvailable = true,
                            ListedDateUtc = new DateTime(2025, 7, 30, 18, 55, 38, 406, DateTimeKind.Utc).AddTicks(1665),
                            MonthlyRent = 1800m,
                            Price = 275000m,
                            PropertyType = "Condo",
                            SquareFeet = 1700,
                            State = "TX",
                            YearBuilt = 2012,
                            ZipCode = "78702"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
